/**
 * IRAH Web Development — SEO Keywords
 * Usage: import { keywords } from "@/components/Keywords";
 *        Then spread into your metadata: keywords: [...keywords]
 */

export const keywords: string[] = [
  // ── Beeramguda (Primary Local) ──
  "web developer Beeramguda",
  "web design Beeramguda",
  "website development Beeramguda",
  "freelance web developer Beeramguda",
  "website designer Beeramguda",
  "web development company Beeramguda",
  "affordable website Beeramguda",
  "best web developer Beeramguda",
  "React developer Beeramguda",
  "Next.js developer Beeramguda",

  // ── Patancheru ──
  "web developer Patancheru",
  "web design Patancheru",
  "website development Patancheru",
  "freelance web developer Patancheru",
  "website designer Patancheru",
  "web development company Patancheru",
  "affordable website Patancheru",
  "best web developer Patancheru",
  "ecommerce website Patancheru",
  "digital marketing Patancheru",

  // ── Patelguda ──
  "web developer Patelguda",
  "web design Patelguda",
  "website development Patelguda",
  "freelance web developer Patelguda",
  "website designer Patelguda",
  "affordable website Patelguda",
  "business website Patelguda",
  "portfolio website Patelguda",

  // ── Medak ──
  "web developer Medak",
  "web design Medak",
  "website development Medak",
  "freelance web developer Medak",
  "website designer Medak",
  "web development company Medak",
  "affordable website Medak",
  "best web developer Medak",
  "ecommerce website Medak",
  "SEO services Medak",

  // ── Hyderabad (Broad Local) ──
  "web developer Hyderabad",
  "web design Hyderabad",
  "website development Hyderabad",
  "freelance web developer Hyderabad",
  "website designer Hyderabad",
  "web development company Hyderabad",
  "affordable web developer Hyderabad",
  "best web developer Hyderabad",
  "web developer near me Hyderabad",
  "cheap website development Hyderabad",
  "professional web developer Hyderabad",
  "web agency Hyderabad",
  "web studio Hyderabad",
  "custom website Hyderabad",
  "responsive website Hyderabad",

  // ── Nearby Areas ──
  "web developer Sangareddy",
  "web developer Miyapur",
  "web developer Kompally",
  "web developer Bachupally",
  "web developer Nizampet",
  "web developer Gachibowli",
  "web developer HITEC City",
  "web developer Kukatpally",
  "web developer Lingampally",
  "web developer Chandanagar",

  // ── Telangana / India ──
  "web developer Telangana",
  "web development India",
  "freelance web developer India",
  "best web developer India",
  "affordable web development India",
  "web developer near me India",
  "React developer India",
  "Next.js developer India",
  "full stack developer India",
  "Node.js developer India",

  // ── Core Tech Stack ──
  "Next.js developer",
  "React developer",
  "TypeScript developer",
  "JavaScript developer",
  "full stack developer",
  "Node.js developer",
  "Tailwind CSS developer",
  "custom web application development",
  "progressive web app development",
  "web app development",
  "frontend developer India",
  "backend developer India",
  "MERN stack developer India",
  "JAMstack developer India",
  "headless CMS development",

  // ── Business Websites ──
  "business website development Hyderabad",
  "startup website development India",
  "landing page design Hyderabad",
  "portfolio website development",
  "portfolio website Hyderabad",
  "blog website development India",
  "restaurant website design Hyderabad",
  "small business website Hyderabad",
  "corporate website design India",
  "company website development Hyderabad",
  "service business website India",
  "doctor website Hyderabad",
  "clinic website design India",
  "lawyer website Hyderabad",
  "gym website design Hyderabad",

  // ── E-commerce ──
  "ecommerce website development Hyderabad",
  "online store development India",
  "Shopify developer Hyderabad",
  "WooCommerce developer India",
  "ecommerce SEO Hyderabad",
  "product catalogue website India",
  "B2B ecommerce website India",
  "ecommerce web design Hyderabad",
  "payment gateway integration India",
  "multi-vendor marketplace development",

  // ── Digital Invitations ──
  "digital wedding invitations India",
  "animated wedding cards online",
  "online wedding invitation Hyderabad",
  "digital wedding card maker India",
  "e-invite for wedding India",
  "WhatsApp wedding invitation India",
  "digital wedding card Hyderabad",
  "personalised wedding invitation India",
  "premium digital invitations Telangana",
  "wedding website India",
  "digital invite maker Hyderabad",
  "custom digital wedding card",

  // ── SEO ──
  "SEO services Hyderabad",
  "local SEO Hyderabad",
  "technical SEO India",
  "on-page SEO services",
  "Google ranking services Hyderabad",
  "website speed optimisation India",
  "SEO audit Hyderabad",
  "keyword research India",
  "Google My Business optimisation Hyderabad",
  "search engine optimisation India",
  "SEO consultant Hyderabad",
  "rank on Google India",
  "organic traffic growth India",

  // ── Maintenance & Support ──
  "website maintenance Hyderabad",
  "website redesign Hyderabad",
  "website revamp India",
  "website bug fix India",
  "website support Hyderabad",
  "website update service India",
  "existing website improvement",
  "website speed fix India",
  "mobile responsive fix India",

  // ── Design ──
  "UI UX design Hyderabad",
  "mobile-first web design India",
  "responsive web design Hyderabad",
  "modern website design India",
  "minimalist website design",
  "website mockup design India",
  "Figma to website India",
  "logo design Hyderabad",
  "brand identity design India",

  // ── Performance & Technical ──
  "fast loading website India",
  "Core Web Vitals optimisation",
  "website performance optimisation",
  "Google PageSpeed optimisation India",
  "secure website development India",
  "SSL certificate setup India",
  "HTTPS website India",
  "website hosting setup India",
  "domain registration India",
  "custom domain setup",

  // ── Pricing Intent ──
  "cheap web developer Hyderabad",
  "low cost website Hyderabad",
  "affordable website design India",
  "budget website development India",
  "website development cost Hyderabad",
  "how much does a website cost India",
  "website packages India",
  "freelance web designer rates India",

  // ── Hire Intent ──
  "hire web developer Hyderabad",
  "hire React developer India",
  "hire Next.js developer India",
  "hire freelance developer Hyderabad",
  "outsource web development India",
  "web developer for hire India",
  "contract web developer India",
  "remote web developer India",

  // ── Industry Specific ──
  "real estate website Hyderabad",
  "hotel website design India",
  "school website development India",
  "education website India",
  "NGO website development India",
  "event management website India",
  "travel website design India",
  "photography portfolio website India",
  "interior designer website India",
  "fashion website development India",

  // ── IRAH Brand ──
  "IRAH web development",
  "IRAH tech Hyderabad",
  "irahtech.in",
  "IRAH website developer",
  "IRAH freelance developer Hyderabad",
];

export default keywords;
